version: '3'
services:
  mysql_db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      #- MYSQL_DATABASE=contas_database
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mysql_db
    command: bash -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 80"
