"""cria tabela de contas a pagar e receber

Revision ID: 330c7f0a7331
Revises: 
Create Date: 2023-06-19 16:50:42.929171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "330c7f0a7331"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contas_a_pagar_e_receber",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.String(length=36), nullable=True),
        sa.Column("valor", sa.Numeric(), nullable=True),
        sa.Column("tipo", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("artists")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column(
            "id",
            mysql.BIGINT(display_width=20),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("first_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("second_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("surname", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "artist_id",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("link", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("extraction_date", mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.drop_table("contas_a_pagar_e_receber")
    # ### end Alembic commands ###
